
spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/zqm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    connectionInitSqls: SET NAMES utf8mb4
    driverClassName: com.mysql.jdbc.Driver
    mapperLocations: classpath*:mapper/**/*Mapper.xml




  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
# You can change the default http port
server:
  port: 8081
  contextPath: /zqm   # 配置后bootRun，访问时要http://localhost:8081/zqm

#logging:
#  level:
#    ROOT: INFO

debug: true


executorPool:
  executorMaxPoolSize: 64
  executorCoreSize: 32
  keepAliveSeconds: 60
  queueCapacity: 10



# Mybatis 配置
mybatis:
  typeAliasesPackage: com.zqm.vo.service.dao
  mapperLocations: classpath:mapper/*Mapper.xml


# jpa 配置
#jpa:
#  database: mysql
#  show-sql: true
#  generate-ddl: true
#  hibernate:
#    ddl-auto: update



#all depend api list
#rest:
